language: python

matrix:
    include:
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6
        - os: osx
          language: generic


notifications:
  email: never

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install virtualenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 -m virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install pip==9; fi
  - openssl aes-256-cbc -K $encrypted_a0055995c7d5_key -iv $encrypted_a0055995c7d5_iv -in .env.enc -out .env -d

install:
  - pip install -r requirements-dev.txt

script:
  - pytest tests/test_utopia_unit.py -v --cov utopia --cov-report term-missing

after_success:
  - coveralls
  - codecov
