language: python

os:
  - linux
  - osx

python:
  - '3.5'
  - '3.6'

notifications:
  email: never

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - openssl aes-256-cbc -K $encrypted_a0055995c7d5_key -iv $encrypted_a0055995c7d5_iv -in .env.enc -out .env -d

install:
  - pip install -r requirements-dev.txt

script:
  - pytest tests/test_utopia_unit.py -v --cov utopia --cov-report term-missing

after_success:
  - coveralls
  - codecov
